# Generated by Django 4.2.4 on 2023-08-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="exam_difficulty",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="train",
            name="exam_seconds",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="train",
            name="exam_tts_play",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="train",
            name="exam_word_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="train",
            name="train_repeat",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="train",
            name="train_seconds",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="train",
            name="train_tts_play",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="train",
            name="train_word_count",
            field=models.IntegerField(default=0),
        ),
    ]
