# Generated by Django 4.2.4 on 2023-08-21 21:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "trains",
            "0002_alter_train_exam_difficulty_alter_train_exam_seconds_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Train",
        ),
    ]
