# Generated by Django 4.2.4 on 2023-08-21 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="id_user",
            field=models.ForeignKey(
                db_column="id_user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
